# Generated by Django 2.0.4 on 2018-04-15 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Fecha de modificación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_advices_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Childs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Fecha de modificación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('document', models.CharField(max_length=20, verbose_name='Documento')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, verbose_name='Genero')),
                ('date_born', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_childs_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_childs_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Fecha de modificación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('age', models.CharField(max_length=3, verbose_name='Edad')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Childs', verbose_name='Niño(a)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_childsdetail_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Fecha de modificación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('document_type', models.CharField(choices=[('Cedula', 'Cédula'), ('Cedula Extranjeria', 'Extranjería')], max_length=100, verbose_name='Tipo de documento')),
                ('document', models.CharField(max_length=20, verbose_name='Documento')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('age', models.CharField(max_length=3, verbose_name='Edad')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, verbose_name='Genero')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('social_stratum', models.CharField(choices=[('0', 'Estrato 0'), ('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=3, verbose_name='Estrato')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_parents_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentsChilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Childs', verbose_name='Niño(a)')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Parents', verbose_name='Adulto')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Fecha de modificación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('name', models.CharField(max_length=150, verbose_name='Parentesco')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_relationship_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_relationship_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeDiagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Fecha de modificación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('name', models.CharField(max_length=150, verbose_name='Tipo Diagnostico')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_typediagnostic_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_typediagnostic_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parents',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Relationship', verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='parents',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_parents_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='childsdetail',
            name='type_diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TypeDiagnostic', verbose_name='Tipo de Diagnostico'),
        ),
        migrations.AddField(
            model_name='childsdetail',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_childsdetail_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='advices',
            name='type_diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TypeDiagnostic', verbose_name='Tipo de Diagnostico'),
        ),
        migrations.AddField(
            model_name='advices',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_advices_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
