# Generated by Django 2.0.4 on 2018-05-01 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typediagnostic',
            name='is_active',
            field=models.BooleanField(verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
