# Generated by Django 2.0.4 on 2018-05-06 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_typediagnostic_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='advices',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typediagnostic',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], verbose_name='Estado'),
        ),
    ]
