# Generated by Django 2.0.5 on 2018-05-08 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180506_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
