# Generated by Django 2.0.4 on 2018-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180501_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typediagnostic',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tipo Diagnostico'),
        ),
    ]
