# Generated by Django 2.0.5 on 2018-05-21 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_relationship_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parents',
            name='document_type',
            field=models.CharField(choices=[('Cédula', 'Cédula'), ('Cedula Extranjería', 'Cedula Extranjería')], max_length=100, verbose_name='Tipo de documento'),
        ),
    ]
