# Generated by Django 2.0.5 on 2018-05-27 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180521_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='document_type',
            field=models.CharField(choices=[('Cédula', 'Cédula'), ('Cédula Extranjería', 'Cédula Extranjería')], max_length=100, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='social_stratum',
            field=models.CharField(choices=[('0', 'Estrato 0'), ('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Otro')], max_length=3, verbose_name='Estrato'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Peso'),
        ),
    ]