# Generated by Django 2.0.5 on 2018-05-27 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180527_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='document',
            field=models.CharField(error_messages={'unique': 'Est documento ya se encuentra registrado.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', code='Inválido', message='Este campo debe ser numérico.'), django.core.validators.MinLengthValidator(6)], verbose_name='Documento'),
        ),
    ]
