# Generated by Django 2.0.5 on 2018-06-06 10:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180527_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='relationship',
        ),
        migrations.AddField(
            model_name='parentschilds',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Relationship', verbose_name='Parentesco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parents',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', code='Inválido', message='Este campo debe ser numérico.'), django.core.validators.MinLengthValidator(10)], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Peso'),
        ),
    ]
