# Generated by Django 2.0.6 on 2018-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180606_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childsdetail',
            name='age',
        ),
        migrations.AlterField(
            model_name='childs',
            name='date_born',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
