# Generated by Django 2.0.6 on 2018-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180610_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentschilds',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
