# Generated by Django 2.0.6 on 2018-06-11 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_parentschilds_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentschilds',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentschilds',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_parentschilds_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentschilds',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='parentschilds',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_parentschilds_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
