# Generated by Django 2.0.6 on 2018-06-16 16:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180611_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='childs',
            name='age_breastfeeding',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Edad en que se abandona la lactancia materna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childs',
            name='child_live',
            field=models.CharField(max_length=150, verbose_name='Con quién vive el menor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childs',
            name='height_born',
            field=models.FloatField(verbose_name='Altura al nacer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childs',
            name='weight_born',
            field=models.FloatField(verbose_name='Peso al nacer'),
            preserve_default=False,
        ),
    ]
