# Generated by Django 2.0.6 on 2018-06-19 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180616_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childs',
            name='age_breastfeeding',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Edad en que se abandona la lactancia materna'),
        ),
    ]
