# Generated by Django 2.0.6 on 2018-07-12 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180619_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childs',
            options={'permissions': (('retrieve_childs', 'Consultar menor'), ('list_childs', 'Consultar menores'))},
        ),
        migrations.AlterModelOptions(
            name='childsdetail',
            options={'permissions': (('retrieve_childsdetail', 'Consultar control del menor'), ('list_childsdetail', 'Consultar controles del menor'))},
        ),
        migrations.AlterModelOptions(
            name='parentschilds',
            options={'permissions': (('retrieve_parentschilds', 'Consultar responsable menor'), ('list_childsdetail', 'Consultar responsables del menor'))},
        ),
        migrations.AlterField(
            model_name='childsdetail',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='childsdetail',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso'),
        ),
    ]
